name: Package Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    
    - name: move to directory
      run: mv dist Construct

    - name: zip artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Construct.zip Construct/

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'Construct.zip'
        releaseId: ${{steps.create_release.outputs.id}}     